---
- hosts: localhost
  connection: local

  vars:
    ssh_key: etcd
    aws_region: eu-west-1
    etcd_num_nodes: 3
    etcd_security_group_name: etcd
    etcd_template: ami-7bf27e0c 
    etcd_instance_type: m1.small

  pre_tasks:
    - name: Get bootstrap token for etcd
      command: curl -w "\n" https://discovery.etcd.io/new
      register: token
    - debug: msg='Etcd token is {{ token.stdout }}'
    
  roles:
    - common-ec2
    - etcd-ec2
