# Create k8s context

  - name: Set context cluster 
    command: kubectl config set-cluster {{ k8s_context_name }} --server=https://{{ k8s_master.default_ip }}:443 --insecure-skip-tls-verify=true
    tags: context

  - name: Set context user
    command: kubectl config set-credentials {{ k8s_context_name }} --username={{ k8s_username }} --password={{ k8s_password}}

  - name: Create context
    command: kubectl config set-context {{ k8s_context_name }} --cluster={{ k8s_context_name }} --user={{ k8s_context_name }}

  - name: Use context
    command: kubectl config use-context {{ k8s_context_name }}
