# Create k8s context

  - name: Set context cluster 
    command: kubectl config set-cluster exo --server=http://{{ k8s_master.default_ip }}:8080 --insecure-skip-tls-verify=true
    tags: context

  - name: Create context
    command: kubectl config set-context exo --cluster=exo

  - name: Use context
    command: kubectl config use-context exo
