# Create Backend security group

  - name: Create etcd Security Group
    ec2_group:
     name: "{{ etcd_security_group_name }}"
     description: etcd
     region: "{{ aws_region }}"
     rules:
       - proto: tcp
         from_port: 22
         to_port: 22
         cidr_ip: 0.0.0.0/0
       - proto: icmp
         from_port: 0
         to_port: 0
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 4001
         to_port: 4001
         group_name: "{{ etcd_security_group_name }}"
       - proto: tcp
         from_port: 7001
         to_port: 7001
         group_name: "{{ etcd_security_group_name }}"
     rules_egress:
       - proto: tcp
         from_port: 0
         to_port: 65535
         cidr_ip: 0.0.0.0/0
